name: 'Ascend base install'
description: 'Ascend project base installer'
type: 'Site'
recipes:
  - poppop_base
install:
  - antibot
  - auto_username
  - autologout
  - content_lock
  - cshs
  - diff
  - easy_breadcrumb
  - entity
  - entity_admin_handlers
  - epp
  - extra_field
  - field_group
  - field_group_table
  - form_mode_manager
  - filefield_paths
  - password_policy
  - password_policy_history
  - password_policy_length
  - password_policy_username
  - pathauto
  - readonly_field_widget
  - redirect
  - role_delegation
  - simple_taxonomy_menu
  - token
  - views_add_button
  - views_bulk_operations
config:
  strict: true
  import:
    antibot: '*'
    cshs: '*'
  actions:
    system.site:
      simpleConfigUpdate:
        page.front: /node/1
        name: 'Ascend'
        mail: 'tech@poppop.studio'
    # Add footer menu to basic page options
    node.type.page:
      simpleConfigUpdate:
        third_party_settings.menu_ui.available_menus:
          - main
          - footer
    gin.settings:
      simpleConfigUpdate:
        # Ideally not, but...
        secondary_toolbar_frontend: true
    filefield_paths.settings:
      simpleConfigUpdate:
        temp_location: 'temporary://filefield_paths'
    # Heavy sigh... This config was already in the installer but password policy
    # nixes it, so I've manually added back fields that its installer borks.
    core.entity_form_display.user.user.default:
      setComponents:
        -
          name: ascend_u_name_first
          options:
            type: string_textfield
            weight: -30
            region: content
            settings:
              size: 60
              placeholder: ''
            third_party_settings: {  }
        -
          name: ascend_u_name_second
          options:
            type: string_textfield
            weight: -20
            region: content
            settings:
              size: 60
              placeholder: ''
            third_party_settings: {  }
    # Can't assign to self using config.
    user.role.user_manager:
      grantPermission: 'assign user_manager role'
    user.role.authenticated:
      grantPermission: 'access toolbar'
    user.role.content_editor:
      grantPermissions:
        - 'edit any page content'
        - 'view page revisions'
        - 'revert page revisions'
