name: 'Ascend base install'
description: 'Ascend project base installer'
type: 'Site'
recipes:
  - poppop_base
install:
  - antibot
  - auto_username
  #- content_lock
  - cshs
  - diff
  - entity
  - entity_admin_handlers
  - epp
  - field_group
  - field_group_table
  - form_mode_manager
  - filefield_paths
  - pathauto
  - readonly_field_widget
  - redirect
  - role_delegation
  - simple_taxonomy_menu
  - token
  - views_add_button
config:
  strict: true
  import:
    antibot: '*'
    cshs: '*'
  actions:
    system.site:
      simpleConfigUpdate:
        page.front: /node/1
        name: 'Ascend'
        mail: 'tech@poppop.studio'
    gin.settings:
      simpleConfigUpdate:
        # Ideally not, but...
        secondary_toolbar_frontend: true
    filefield_paths.settings:
      simpleConfigUpdate:
        temp_location: 'temporary://filefield_paths'
    # Can't assign to self using config.
    user.role.user_manager:
      grantPermission: 'assign user_manager role'
    user.role.authenticated:
      grantPermission: 'access toolbar'
    user.role.content_editor:
      grantPermissions:
        - 'edit any page content'
        - 'view page revisions'
        - 'revert page revisions'
